// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/projects/[projectId]" | "/app/projects/[projectId]/assistant" | "/app/projects/[projectId]/conflicts" | "/app/projects/[projectId]/conflicts/[conflictId]" | "/app/projects/[projectId]/documents" | "/app/projects/[projectId]/documents/[documentId]" | "/app/projects/[projectId]/exports" | "/app/projects/[projectId]/graph" | "/app/projects/[projectId]/requirements" | "/app/projects/[projectId]/requirements/[requirementId]" | "/app/projects/[projectId]/risks" | "/app/projects/[projectId]/scope" | "/app/projects/[projectId]/traceability"
type AppRouteHandlerRoutes = "/api/projects/[projectId]/assistant" | "/api/projects/[projectId]/export/[report]" | "/api/projects/[projectId]/ingest"
type PageRoutes = never
type LayoutRoutes = "/" | "/app" | "/app/projects/[projectId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/projects/[projectId]/assistant": { "projectId": string; }
  "/api/projects/[projectId]/export/[report]": { "projectId": string; "report": string; }
  "/api/projects/[projectId]/ingest": { "projectId": string; }
  "/app": {}
  "/app/projects/[projectId]": { "projectId": string; }
  "/app/projects/[projectId]/assistant": { "projectId": string; }
  "/app/projects/[projectId]/conflicts": { "projectId": string; }
  "/app/projects/[projectId]/conflicts/[conflictId]": { "projectId": string; "conflictId": string; }
  "/app/projects/[projectId]/documents": { "projectId": string; }
  "/app/projects/[projectId]/documents/[documentId]": { "projectId": string; "documentId": string; }
  "/app/projects/[projectId]/exports": { "projectId": string; }
  "/app/projects/[projectId]/graph": { "projectId": string; }
  "/app/projects/[projectId]/requirements": { "projectId": string; }
  "/app/projects/[projectId]/requirements/[requirementId]": { "projectId": string; "requirementId": string; }
  "/app/projects/[projectId]/risks": { "projectId": string; }
  "/app/projects/[projectId]/scope": { "projectId": string; }
  "/app/projects/[projectId]/traceability": { "projectId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
  "/app/projects/[projectId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
