// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/conflicts/[conflictId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/conflicts/[conflictId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/conflicts/[conflictId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/conflicts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/conflicts">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/conflicts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/documents/[documentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/documents/[documentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/exports">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/graph/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/graph">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/graph/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/requirements/[requirementId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/requirements/[requirementId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/requirements/[requirementId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/requirements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/requirements">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/requirements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/risks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/risks">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/risks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/scope/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/scope">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/scope/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/traceability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/projects/[projectId]/traceability">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/traceability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/export/[report]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/export/[report]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/export/[report]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/ingest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/ingest">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/ingest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/projects/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/app/projects/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
