// AUTO-GENERATED from demo-data/. Edit the source files, then run:
//   node scripts/sync-demo-data.mjs
//
// The Meridian Bank engagement corpus. Every requirement, conflict, ambiguity
// and risk the product shows is derived from the text below at seed time -
// nothing in the demo is hand-written into the database.

export interface DemoDocument {
  title: string;
  kind: string;
  filename: string;
  author: string | null;
  capturedAt: string;
  content: string;
}

export const DEMO_CORPUS: DemoDocument[] = [
  {
    "title": "Engagement Brief - Customer Onboarding Platform",
    "kind": "specification",
    "filename": "01-engagement-brief.md",
    "author": "Priya Raghavan",
    "capturedAt": "2026-06-08",
    "content": "# Engagement Brief: Meridian Bank Customer Onboarding Platform\n\nPrepared by Northgate Advisory for Meridian Bank plc. Distribution: steering\ncommittee only.\n\n## 1. Background\n\nMeridian Bank currently onboards personal current account customers through a\nbranch-first process supported by a 2014-era origination system. Average time to\naccount activation is 6.5 working days. Digital abandonment on the existing web\nform runs at 61%.\n\nMeridian has appointed Northgate Advisory to run a 10-week discovery and to\ndeliver the target-state customer onboarding platform.\n\n## 2. Scope baseline\n\nThe following sits inside the agreed scope baseline as of the date of this\nbrief. Anything added after the baseline date of 24 July 2026 must pass through\nthe change control process defined in section 7 of the master services\nagreement.\n\n- Personal current account onboarding for UK-resident retail customers.\n- Identity verification, sanctions screening and politically exposed person\n  screening.\n- Application status tracking for the customer and for the branch network.\n- Handoff of activated accounts into the existing core banking platform.\n\n## 3. Out of scope\n\n- Business and commercial account onboarding.\n- Mortgage and secured lending origination.\n- Replacement of the core banking platform itself.\n\n## 4. Success criteria\n\nThe programme must reduce median time to account activation from 6.5 working\ndays to under 1 working day. The programme should reduce digital abandonment on\nthe onboarding journey below 30%.\n\n## 5. Delivery approach\n\nDiscovery runs from 8 June 2026 to 14 August 2026 and comprises twelve\nstakeholder workshops, a documentation review and a technical assessment of the\nincumbent origination platform. Build commences 1 September 2026.\n\n## 6. Constraints acknowledged at kick-off\n\nThe platform must be delivered on Meridian's existing private cloud tenancy. The\nprogramme must not require a change to the core banking platform's published\nintegration contract during the initial release.\n"
  },
  {
    "title": "Workshop 01 Transcript - Onboarding Journey",
    "kind": "transcript",
    "filename": "02-workshop-01-onboarding-journey.md",
    "author": "Northgate Advisory",
    "capturedAt": "2026-06-12",
    "content": "# Workshop 01 - Target Onboarding Journey\n\nDate: 12 June 2026. Location: Meridian Bank, Canary Wharf. Facilitator: Priya\nRaghavan (Northgate Advisory). Recording transcribed automatically, lightly\ncorrected for readability.\n\nDANIEL OKAFOR (Head of Retail Product, Meridian Bank): Let me set the ambition.\nToday a customer who wants a current account has to book a branch appointment or\nfill in a web form that then dumps them into a branch appointment anyway. That\nhas to stop. A customer must be able to open a personal current account without\nvisiting a branch.\n\nPRIYA RAGHAVAN (Engagement Lead, Northgate Advisory): End to end, including\nidentity checks?\n\nDANIEL OKAFOR: End to end. If we cannot verify them digitally then yes, they get\nrouted to a branch, but that should be the exception, not the default path.\n\nDANIEL OKAFOR: Second thing. We know a lot about our existing customers already.\nIf someone already banks with us for savings and they apply for a current\naccount, the system must pre-fill application data from the existing customer\nrecord. Making them retype their address is how we lose people.\n\nAISHA BELL (Customer Experience Lead, Meridian Bank): I want to add to that. The\ncustomer must be able to save a partially completed application and resume it on\na different device within 14 days.\n\nPRIYA RAGHAVAN: Fourteen days specifically?\n\nAISHA BELL: Fourteen. That is what our retention team modelled. After fourteen\ndays the lead is cold anyway.\n\nDANIEL OKAFOR: On status. Right now customers call the contact centre to ask\nwhere their application is. The system must show the customer the current status\nof their application and the expected completion date.\n\nMARCUS TRAN (Branch Operations Manager, Meridian Bank): Branch staff need the\nsame view. If a customer walks in, the colleague in front of them must be able to\nsee exactly the same application status the customer sees.\n\nPRIYA RAGHAVAN: Noted. Any hard rules about who can see what?\n\nMARCUS TRAN: Branch colleagues should not be able to see the customer's credit\ndecision rationale, only the status. That is a compliance thing, Sofia can\nconfirm.\n\nDANIEL OKAFOR: One more. When the account is activated it must appear in the\ncore banking platform within 15 minutes so the customer can use it immediately.\n\nPRIYA RAGHAVAN: That is a hard integration requirement, I will take it to the\ntechnical workshop.\n\nAISHA BELL: And the journey has to work on a phone. Most of our applicants start\non mobile. The onboarding journey must be fully usable on a mobile browser\nwithout installing an application.\n\nDANIEL OKAFOR: Agreed. Mobile web first.\n"
  },
  {
    "title": "Workshop 03 Notes - Risk, KYC and Financial Crime",
    "kind": "meeting_notes",
    "filename": "03-workshop-03-risk-compliance.md",
    "author": "Sofia Lindqvist",
    "capturedAt": "2026-06-24",
    "content": "# Workshop 03 - Risk, KYC and Financial Crime\n\nDate: 24 June 2026. Attendees: Sofia Lindqvist (Head of Financial Crime\nCompliance, Meridian Bank), Priya Raghavan (Northgate Advisory), Tom Devlin\n(Solution Architect, Northgate Advisory), Ruth Menzies (Data Protection Officer,\nMeridian Bank, part session).\n\nThese are working notes taken in the room. They were not circulated as formal\nminutes and have not been incorporated into the product specification.\n\n## Identity and screening\n\nSofia walked through the regulatory position. The bank operates under the Money\nLaundering Regulations and its own internal financial crime standard MB-FC-004.\n\n- The system must complete identity verification against the sanctions and AML\n  watchlist before an account is activated. Sofia was explicit that activation\n  before screening completes is not acceptable under any circumstances.\n- The system must screen every applicant for politically exposed person status\n  at application and re-screen on a rolling 12-month cycle.\n- The system must retain a full audit trail of every KYC decision, including\n  which rule fired, the data the decision was based on, and the operator who\n  overrode it where an override occurred.\n- Where an automated screening decision is overridden, the system must record\n  the identity of the approver and a free-text justification.\n\nSofia: \"If the regulator asks me in two years why we opened an account for\nsomeone, I need to be able to answer that in five minutes, not five weeks.\"\n\n## Suspicious activity\n\n- The system must allow a financial crime analyst to place an application on\n  hold without notifying the applicant of the reason.\n\nTom flagged that \"without notifying the applicant\" has UI implications - the\nstatus shown to the customer must not reveal a financial crime hold. Sofia\nconfirmed the customer-visible status should read as \"in review\".\n\n## Data handling\n\nRuth joined for twenty minutes.\n\n- Customer identity records must be retained for seven years from the date of\n  account closure, per the bank's records retention schedule.\n\nRuth noted she would come back separately on abandoned applications because the\nposition there is different and she wanted to check it with legal first.\n\n## Open items\n\nSofia asked that these notes be worked into the specification before build\nstarts. Priya to action.\n"
  },
  {
    "title": "Workshop 05 Transcript - Customer Experience",
    "kind": "transcript",
    "filename": "04-workshop-05-customer-experience.md",
    "author": "Northgate Advisory",
    "capturedAt": "2026-07-02",
    "content": "# Workshop 05 - Customer Experience and Accessibility\n\nDate: 2 July 2026. Facilitator: Priya Raghavan. Transcribed automatically.\n\nAISHA BELL (Customer Experience Lead, Meridian Bank): The number that keeps me\nawake is 61% abandonment. When we interviewed people who dropped out, the two\nwords that came back were \"slow\" and \"confusing\".\n\nPRIYA RAGHAVAN (Engagement Lead, Northgate Advisory): So what does good look\nlike?\n\nAISHA BELL: The application must have fast response time so customers do not\nabandon the journey. That is the headline.\n\nPRIYA RAGHAVAN: Can we put a number on fast?\n\nAISHA BELL: I would rather not commit to a number in the room. It needs to feel\ninstant. Engineering can tell us what is achievable.\n\nAISHA BELL: The second one is comprehension. The interface should be easy to use\nfor customers who are not comfortable with digital banking. A meaningful share of\nour applicants are over sixty.\n\nMARCUS TRAN (Branch Operations Manager, Meridian Bank): We see that in branch\nconstantly. People give up at the income and employment section.\n\nAISHA BELL: Right. So the system must explain in plain language why each piece of\ninformation is being requested.\n\nPRIYA RAGHAVAN: Accessibility standard?\n\nAISHA BELL: This one I can be precise about because it is a bank policy. The\nonboarding journey must conform to WCAG 2.2 Level AA. That is non-negotiable, it\nis in our accessibility policy and we have been audited against it before.\n\nAISHA BELL: And the journey must be available in English and Welsh.\n\nPRIYA RAGHAVAN: Welsh because of the branch footprint?\n\nAISHA BELL: Statutory. We have branches in Wales.\n\nAISHA BELL: Last one from me. If the customer gets stuck, the system should offer\na handover to a human adviser without losing the data already entered.\n\nMARCUS TRAN: That is a big one for us. Today the handover means starting again.\n\nAISHA BELL: And it needs to be a good experience, not a jarring one. The design\nshould feel modern and reassuring.\n\nPRIYA RAGHAVAN: I will capture that as a design principle rather than a\nrequirement, it is not testable as written.\n"
  },
  {
    "title": "Workshop 07 Transcript - Performance and Scale",
    "kind": "transcript",
    "filename": "05-workshop-07-performance-scale.md",
    "author": "Northgate Advisory",
    "capturedAt": "2026-07-09",
    "content": "# Workshop 07 - Performance, Scale and Resilience\n\nDate: 9 July 2026. Facilitator: Tom Devlin (Solution Architect, Northgate\nAdvisory). Transcribed automatically.\n\nTOM DEVLIN (Solution Architect, Northgate Advisory): I want to leave this room\nwith numbers, not adjectives. Kenji, what does the traffic actually look like?\n\nKENJI MORI (Platform Engineering Lead, Meridian Bank): Our peak is Monday\nmorning, roughly 08:00 to 10:00. On a normal Monday the existing origination\nfront end sees about 1,400 concurrent sessions. On the Monday after a marketing\npush we have seen 4,100.\n\nTOM DEVLIN: And the target state?\n\nKENJI MORI: Product are forecasting a step change because we are removing the\nbranch bottleneck. The platform must support 10,000 concurrent users during the\nMonday morning peak. That is the number we have been asked to build to.\n\nTOM DEVLIN: Where did 10,000 come from?\n\nKENJI MORI: Daniel's team modelled it off the digital-first competitors. I will\nbe honest, I think it is optimistic, but it is the number in the product forecast\nand it is what we have been told to design for.\n\nTOM DEVLIN: Fine, I will record it as stated. Latency?\n\nKENJI MORI: The system must return 95% of API responses within 500 milliseconds\nunder normal operating load.\n\nTOM DEVLIN: Normal being the 1,400 figure or the 10,000 figure?\n\nKENJI MORI: Normal being everyday load. Under peak we would accept degradation as\nlong as nothing times out.\n\nTOM DEVLIN: What about the full journey?\n\nKENJI MORI: Onboarding application submission must complete within 90 seconds end\nto end, including the identity and screening calls. The screening vendor is the\nlong pole there.\n\nTOM DEVLIN: Scaling approach?\n\nKENJI MORI: The system should scale horizontally without a service interruption.\nWe are on the private cloud tenancy so that means adding pods, and we need the\nautoscaler configured properly this time.\n\nTOM DEVLIN: Resilience?\n\nKENJI MORI: The platform must achieve 99.99% availability measured monthly,\nexcluding planned maintenance windows. That is the tier-1 service standard and\nonboarding has been classified tier-1.\n\nTOM DEVLIN: That is 4.3 minutes of unplanned downtime a month. You are confident\nthe tenancy supports that?\n\nKENJI MORI: With multi-zone, yes. Single zone, no.\n\nTOM DEVLIN: Then the platform must be deployed across at least two availability\nzones. I am recording that as a derived requirement, it follows from the\navailability target rather than from anyone asking for it directly.\n\nKENJI MORI: Agreed. One more. The system must process at least 2,000 account\nactivations per hour at peak so we do not build a queue behind the screening\nstep.\n"
  },
  {
    "title": "Email - Infrastructure budget envelope for onboarding platform",
    "kind": "email",
    "filename": "06-email-finance-infrastructure-budget.md",
    "author": "Helena Vosloo",
    "capturedAt": "2026-06-19",
    "content": "From: Helena Vosloo <helena.vosloo@meridianbank.example>\nTo: Priya Raghavan <p.raghavan@northgate-advisory.example>\nCc: Daniel Okafor, Kenji Mori, Programme Mailbox\nDate: Friday 19 June 2026, 17:42\nSubject: RE: Onboarding platform - cost envelope for discovery\n\nPriya,\n\nFollowing the capital committee on Wednesday, I can now give you the envelope\nyou asked for in week one.\n\nInfrastructure spend for the onboarding platform must not exceed $200,000 in the\nfirst twelve months of operation. That figure covers compute, storage, network\nand the private cloud tenancy uplift. It does not cover the screening vendor\nlicence, which sits in the financial crime cost centre, and it does not cover\nNorthgate's fees.\n\nAny spend above that threshold requires a separate capital request, which in\npractice means the November committee at the earliest and a three to four month\ndelay. I would strongly prefer we design inside the envelope rather than plan for\nan uplift we may not get.\n\nTwo further points the committee asked me to pass on:\n\nThe programme must deliver measurable benefit within the first financial year.\nThe committee's patience for multi-year payback on digital projects is thin at\nthe moment.\n\nLicence and vendor commitments must be structured so they can be exited within\ntwelve months. We have been burned on a five-year contract before.\n\nI am copying Kenji so engineering has the number early. Kenji, if the\narchitecture you are designing cannot live inside $200k please tell me now and\nnot in December.\n\nBest,\nHelena\n\n--\nHelena Vosloo\nFinance Business Partner, Retail Technology\nMeridian Bank plc\n"
  },
  {
    "title": "Security Review Meeting Notes",
    "kind": "meeting_notes",
    "filename": "07-security-review-notes.md",
    "author": "Owen Pritchard",
    "capturedAt": "2026-07-16",
    "content": "# Security Design Review - Session 1\n\nDate: 16 July 2026. Attendees: Owen Pritchard (Chief Information Security\nOfficer, Meridian Bank), Tom Devlin (Solution Architect, Northgate Advisory),\nKenji Mori (Platform Engineering Lead, Meridian Bank).\n\nNotes taken by Owen Pritchard.\n\n## General position\n\nOnboarding handles identity documents, biometric selfies and full customer\npersonal data. It is the highest-sensitivity data class the retail bank holds.\n\nThe platform must be secure. I will not sign off a design that treats security as\na later phase.\n\n## Specific points raised\n\n- Customer credentials must be stored using industry standard encryption.\n- The system must encrypt all personal data at rest and in transit.\n- The system must enforce multi-factor authentication for all staff users\n  accessing the administration console.\n- The system must log every access to a customer's identity documents, including\n  the identity of the staff member and the business justification selected.\n- Session tokens must expire after 15 minutes of inactivity for staff users.\n- The system must not store raw identity document images for longer than is\n  necessary to complete verification.\n\nTom asked what \"longer than necessary\" means in days. I said I would come back\nafter speaking with Ruth. This is still open.\n\n## Penetration testing\n\nAn independent penetration test must be completed before the platform processes\nlive customer data. Remediation of any critical or high finding must be\ncompleted before go-live.\n\n## Third parties\n\nThe screening vendor connection must terminate inside Meridian's network\nperimeter. No direct browser-to-vendor calls carrying customer data.\n\n## Actions\n\n- Owen to define the retention period for raw document images.\n- Tom to produce a threat model before the end of discovery.\n- Kenji to confirm the tenancy supports customer-managed encryption keys.\n"
  },
  {
    "title": "Product Specification v0.4 (extract)",
    "kind": "specification",
    "filename": "08-product-specification-v04.md",
    "author": "Daniel Okafor",
    "capturedAt": "2026-07-21",
    "content": "# Customer Onboarding Platform - Product Specification v0.4\n\nStatus: draft, circulated for comment. Sections 1 to 3 omitted from this extract.\n\n## Section 4 - Non-functional characteristics\n\n### 4.1 Availability\n\nThe service is classified tier-1. The platform must achieve 99.99% availability\nmeasured monthly, excluding agreed planned maintenance windows.\n\n### 4.2 Capacity and throughput\n\nThe service must sustain 10,000 concurrent sessions at peak without degradation\nof the published latency targets.\n\nCapacity headroom of 30% above forecast peak must be maintained at all times.\n\n### 4.3 Latency\n\nThe system must return 95% of API responses within 500 milliseconds under normal\noperating load. The 99th percentile must remain below 1,500 milliseconds.\n\n### 4.4 Recoverability\n\nThe recovery point objective for customer application data must not exceed 5\nminutes.\n\n## Section 5 - Functional summary\n\n### 5.1 Application capture\n\nThe system must allow a customer to complete a personal current account\napplication entirely online.\n\nThe system must validate the applicant's address against the Royal Mail postcode\naddress file.\n\n### 5.2 Decisioning\n\nThe system must apply the bank's published eligibility criteria automatically and\nreturn a decision without manual intervention in at least 80% of applications.\n\nThe system must allow an underwriter to review and override an automated\ndecision.\n\n### 5.3 Integration\n\nThe system must publish an account activation event to the core banking platform\nwithin 15 minutes of activation.\n\nThe system must integrate with the incumbent screening vendor using the existing\nenterprise service bus.\n\n## Section 6 - Assumptions\n\nThe following are assumptions carried by the product team. They have not been\nindependently verified.\n\n- It is assumed the screening vendor can sustain the peak throughput implied by\n  section 4.2.\n- It is assumed the private cloud tenancy supports multi-zone deployment without\n  a commercial change.\n- It is assumed existing customer records are of sufficient quality to support\n  pre-fill without manual correction.\n"
  },
  {
    "title": "Records Retention Schedule (extract) MB-DG-011",
    "kind": "policy",
    "filename": "09-records-retention-policy-extract.md",
    "author": "Meridian Bank Data Governance",
    "capturedAt": "2026-06-30",
    "content": "# MB-DG-011 Records Retention Schedule - Retail Banking (extract)\n\nVersion 7.2. Owner: Data Governance. Approved by the Group Records Committee.\n\n## 3. Customer identity and onboarding records\n\n### 3.1 Identity verification records\n\nCustomer identity records must be retained for seven years from the date of\naccount closure. This period is set by the Money Laundering Regulations and is\nnot discretionary.\n\nIdentity records in scope of this clause include the verified name, date of\nbirth, residential address history, the identity document reference and the\noutcome of each verification check.\n\n### 3.2 Screening outcomes\n\nSanctions, politically exposed person and adverse media screening outcomes must\nbe retained for seven years from the date of the screening event.\n\n### 3.3 Decision records\n\nAccount opening decision records, including the rationale for any manual\noverride, must be retained for seven years from the date of the decision.\n\n### 3.4 Raw document images\n\nImages of identity documents captured during onboarding are held under a separate\ndisposal rule which is currently under review by the Data Protection Office. The\nprevailing instruction is that images must be disposed of once verification is\ncomplete and the verification outcome has been recorded.\n\n## 4. Applications not proceeding to account opening\n\nThis section is currently under review. Refer queries to the Data Protection\nOfficer.\n\n## 5. Legal hold\n\nWhere a record is subject to a legal hold, the retention periods in section 3 are\nsuspended and the record must not be disposed of until the hold is lifted.\n"
  },
  {
    "title": "Email - Abandoned application data, position confirmed",
    "kind": "email",
    "filename": "10-email-dpo-abandoned-applications.md",
    "author": "Ruth Menzies",
    "capturedAt": "2026-07-28",
    "content": "From: Ruth Menzies <ruth.menzies@meridianbank.example>\nTo: Priya Raghavan <p.raghavan@northgate-advisory.example>, Tom Devlin\nCc: Sofia Lindqvist, Owen Pritchard\nDate: Tuesday 28 July 2026, 09:14\nSubject: Abandoned applications - confirmed position from Legal\n\nPriya, Tom,\n\nFollowing up on the action from Workshop 03. Legal have now confirmed the\nposition on applications that do not proceed to an account being opened.\n\nPersonal data captured in abandoned applications must be deleted within 30 days\nof the application being marked abandoned. An application is marked abandoned if\nthe applicant takes no action for 30 consecutive days, so the practical maximum\nlifetime of that data is 60 days from last activity.\n\nTo be clear about why: where no account is opened, no customer relationship\nexists, and the Money Laundering Regulations retention obligation does not\nattach. Holding that data longer is a data minimisation breach, and we have had a\nsupervisory conversation about exactly this in another part of the group.\n\nThe system must delete all personal data associated with an abandoned\napplication, including any partially uploaded identity document images.\n\nTwo things I want to flag before you write this into the specification.\n\nFirst, I am aware the retention schedule MB-DG-011 says seven years. That clause\nis written for customers. It does not read cleanly for non-customers and I am\nraising a change to section 4 of the schedule. Until that change lands, the two\ndocuments will appear to disagree, and I would rather the programme design to\nthis email than to the schedule.\n\nSecond, if screening has already produced a positive sanctions match on an\nabandoned application, that is a different case and the record must be retained\nunder the financial crime standard. Sofia, please confirm you agree.\n\nRuth\n\n--\nRuth Menzies\nData Protection Officer\nMeridian Bank plc\n"
  },
  {
    "title": "Email - Broker-introduced applications in release 1",
    "kind": "email",
    "filename": "11-email-broker-channel-scope.md",
    "author": "Nathan Cole",
    "capturedAt": "2026-08-06",
    "content": "From: Nathan Cole <nathan.cole@meridianbank.example>\nTo: Daniel Okafor, Priya Raghavan <p.raghavan@northgate-advisory.example>\nCc: Helena Vosloo, Programme Mailbox\nDate: Thursday 6 August 2026, 16:05\nSubject: Broker channel - needs to be in release 1\n\nDaniel, Priya,\n\nI know discovery is nearly closed but this has come from the growth review on\nTuesday and it is not optional from a commercial standpoint.\n\nThirty-one per cent of our new current account volume last year came through\nintroducer relationships. If the new platform only serves direct applicants we\nwill be running two origination systems for another eighteen months, and the\nbroker experience stays on the 2014 stack.\n\nSo: the onboarding platform must also support broker-introduced applications in\nrelease 1.\n\nPractically that means a few things.\n\nThe system must allow an authorised broker to submit an application on behalf of\na customer. The system must provide a partner dashboard where a broker can see\nthe status of every application they have introduced. The system must calculate\nand record introducer commission against each activated account.\n\nI appreciate the baseline was signed on 24 July and this lands after it. I am\nhappy to take it through change control, but I want it understood that the\ncommercial case for the programme was built assuming broker volume, so treating\nit as a phase 2 item undermines the benefit numbers Helena is holding us to.\n\nCan we discuss on Monday.\n\nNathan\n\n--\nNathan Cole\nDirector, Intermediary Distribution\nMeridian Bank plc\n"
  },
  {
    "title": "Operational Readiness Call Transcript",
    "kind": "transcript",
    "filename": "12-ops-readiness-call.md",
    "author": "Northgate Advisory",
    "capturedAt": "2026-07-30",
    "content": "# Operational Readiness Call\n\nDate: 30 July 2026. Dial-in. Transcribed automatically.\n\nGRACE ADEYEMI (Service Operations Manager, Meridian Bank): My concern is what\nhappens at 3am when this breaks and my team has to deal with it.\n\nTOM DEVLIN (Solution Architect, Northgate Advisory): Fair. What do you need?\n\nGRACE ADEYEMI: The platform should provide high availability. That is the first\nthing.\n\nTOM DEVLIN: Kenji gave me 99.99% monthly in Workshop 07. Is that the same thing\nyou mean?\n\nGRACE ADEYEMI: I think so, but I would want to see it written down against a\nmeasurement window. People say high availability and mean very different things.\n\nGRACE ADEYEMI: Recovery. The recovery time objective must be under 4 hours for a\nfull service restoration.\n\nTOM DEVLIN: Under four hours for full restoration, understood. I will note that\nsits alongside the availability target rather than replacing it.\n\nGRACE ADEYEMI: Monitoring. The system must emit health and error metrics to the\nexisting observability platform. If it does not appear on our dashboards it does\nnot exist as far as my team is concerned.\n\nGRACE ADEYEMI: The system must raise an alert to the on-call channel within 2\nminutes of an application submission failure rate exceeding 5% over a rolling 5\nminute window.\n\nTOM DEVLIN: That is specific, thank you.\n\nGRACE ADEYEMI: We learned that one the hard way on the payments migration.\n\nGRACE ADEYEMI: Runbooks. The supplier must provide operational runbooks for every\nalert condition before the platform enters production.\n\nGRACE ADEYEMI: Maintenance. Planned maintenance must be performed within the\nagreed change window of Sunday 02:00 to 06:00.\n\nTOM DEVLIN: Anything on capacity management?\n\nGRACE ADEYEMI: The system should provide capacity headroom reporting so we can\nsee the trend before we hit a wall. Nothing fancy, a weekly number is fine.\n\nTOM DEVLIN: Noted. Support model?\n\nGRACE ADEYEMI: Third line stays with the build team for the first six months\nafter go-live. That is a commercial point for Helena, but operationally I need it.\n"
  },
  {
    "title": "Email thread - Go-live date and regulatory observation period",
    "kind": "email",
    "filename": "13-email-go-live-date.md",
    "author": "Daniel Okafor",
    "capturedAt": "2026-08-11",
    "content": "From: Daniel Okafor <daniel.okafor@meridianbank.example>\nTo: Programme Distribution\nDate: Tuesday 11 August 2026, 11:20\nSubject: Go-live date confirmed\n\nAll,\n\nThe steering committee has confirmed the date. The platform must go live on 2\nMarch 2027. This is now a board-level commitment and it has been communicated to\nthe group executive.\n\nBuild starts 1 September. That gives us six months.\n\nDaniel\n\n---\n\nFrom: Sofia Lindqvist <sofia.lindqvist@meridianbank.example>\nTo: Daniel Okafor, Programme Distribution\nDate: Tuesday 11 August 2026, 14:47\nSubject: RE: Go-live date confirmed\n\nDaniel,\n\nI need to raise a sequencing problem rather than object to the date itself.\n\nRegulatory sign-off for a new onboarding channel requires a 12-week observation\nperiod, which must commence after user acceptance testing completes and must run\non production-equivalent data. That is the standard the Financial Crime Committee\napplied to the digital savings launch and I have no basis to ask for a shorter\none here.\n\nIf UAT completes at the end of January, twelve weeks of observation takes us into\nlate April. I do not see how 2 March works unless UAT completes in early\nDecember, which would mean build finishing in about ten weeks.\n\nI am not trying to be difficult. I would rather we have this conversation in\nAugust than in February.\n\nSofia\n\n---\n\nFrom: Daniel Okafor <daniel.okafor@meridianbank.example>\nTo: Sofia Lindqvist, Programme Distribution\nDate: Tuesday 11 August 2026, 16:02\nSubject: RE: RE: Go-live date confirmed\n\nSofia,\n\nUnderstood. Let me take this back to steering. In the meantime the date stands as\nthe planning assumption and the team should work to it.\n\nDaniel\n"
  },
  {
    "title": "Discovery Wrap-up Session Notes",
    "kind": "meeting_notes",
    "filename": "14-discovery-wrapup-notes.md",
    "author": "Northgate Advisory",
    "capturedAt": "2026-08-14",
    "content": "# Discovery Wrap-up - Open Items Sweep\n\nDate: 14 August 2026. Open floor session. Attendance not formally recorded.\n\nThe purpose of the session was to sweep up anything raised during discovery that\nhad not landed in a workshop. Items below were called out from the floor. Where\nthe notes do not name a requester, the transcription did not capture who was\nspeaking.\n\n## Items raised\n\n- The system must provide a manual override for relationship managers so a\n  priority customer can be progressed ahead of the queue.\n\n- The system must support a paper application path for customers who cannot\n  complete the journey digitally.\n\n- The platform must integrate with the branch appointment booking system so a\n  failed digital verification can be converted into a branch appointment in one\n  step.\n\n- The system should retain the applicant's uploaded documents so they do not\n  have to be re-uploaded if the application is reopened.\n\n- The system must produce a monthly management information pack covering\n  application volume, conversion, abandonment stage and average time to\n  activation.\n\n- Somebody asked whether we are handling joint applications. No decision taken.\n  Carried as an open question.\n\n## Facilitator note\n\nSeveral of these items arrived without an identified owner. Priya flagged in the\nroom that items without a named business owner cannot be taken into build,\nbecause there is nobody to sign off the acceptance criteria. The manual override\nitem in particular was raised twice in discovery and has still not been claimed by\na named individual.\n\n## Next steps\n\nRequirements register to be finalised and issued for sign-off by 21 August 2026.\n"
  },
  {
    "title": "Stakeholder Register",
    "kind": "csv",
    "filename": "15-stakeholder-register.csv",
    "author": "Northgate Advisory",
    "capturedAt": "2026-06-08",
    "content": "name,role,org,team,email,influence\nDaniel Okafor,Head of Retail Product,Meridian Bank,Product,daniel.okafor@meridianbank.example,high\nAisha Bell,Customer Experience Lead,Meridian Bank,Product,aisha.bell@meridianbank.example,medium\nKenji Mori,Platform Engineering Lead,Meridian Bank,Engineering,kenji.mori@meridianbank.example,high\nHelena Vosloo,Finance Business Partner,Meridian Bank,Finance,helena.vosloo@meridianbank.example,high\nSofia Lindqvist,Head of Financial Crime Compliance,Meridian Bank,Compliance,sofia.lindqvist@meridianbank.example,high\nRuth Menzies,Data Protection Officer,Meridian Bank,Compliance,ruth.menzies@meridianbank.example,high\nOwen Pritchard,Chief Information Security Officer,Meridian Bank,Security,owen.pritchard@meridianbank.example,high\nGrace Adeyemi,Service Operations Manager,Meridian Bank,Operations,grace.adeyemi@meridianbank.example,medium\nMarcus Tran,Branch Operations Manager,Meridian Bank,Operations,marcus.tran@meridianbank.example,medium\nNathan Cole,Director Intermediary Distribution,Meridian Bank,Distribution,nathan.cole@meridianbank.example,medium\nPriya Raghavan,Engagement Lead,Northgate Advisory,Delivery,p.raghavan@northgate-advisory.example,high\nTom Devlin,Solution Architect,Northgate Advisory,Delivery,t.devlin@northgate-advisory.example,medium\n"
  }
];
